# **Experimentos da semana 1:**

# Inicializando com tiktoken


# Criando meu tokenizer

In [1]:
import re
import urllib.request

def pre_tokenizer(text):
  result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
  result = [item for item in result if item.strip()]

  return result

In [2]:
#Testando em shakespeare:

url = "https://www.gutenberg.org/files/100/100-0.txt"
file_path = "shakespeare.txt"

urllib.request.urlretrieve(url, file_path)

with open(file_path, "r", encoding="utf-8") as f:
    text = f.read()

result = pre_tokenizer(text)
vocabulary = list(set(result))
vocabulary.extend(["<UNK>", "<PAD>"])
vocab_size = len(vocabulary)

print(vocabulary)
print(vocab_size)

['Changes', 'Cram', 'combat', 'prosperously', '[Exit', 'strangers’', 'th’vein', 'Appear', 'ding', 'Since', 'hammers', 'extend', 'repined', 'auger’s', 'APPARITIONS', '“sirrah”', 'deem’st', 'ruling', 'peregrinate', 'unhopefullest', 'mayor', 'grievance', 'Raining', 'sporting-place', 'attaint', '“Hem', 'out-vied', 'Laid', 'ruby', '[sings', 'Chequering', 'Intolerable', 'team', 'Disguised', 'très', 'prudent', 'foist', 'recounted', 'Actaeon’s', 'rackets', 'straining', 'Several', '1141', 'expert', 'syrups', 'easy-held', '“reproof', 'unbraced', 'defier', 'cunning’st', 'puzzles', 'Profess', 'couched', '—Would', 'shrugs', 'dined—which', 'pope', 'gardeners', 'Pig-like', 'profaneness', 'Swallows', 'Ear’s', 'wiselier', 'pouncet-box', 'ego', 'littered', 'honouring', 'poise', 'meteors', 'Byzantium', '868', 'whose', 'why—hates', 'acture', 'Manhood', 'drowning', 'dissension', 'egregiously', 'Calchas', 'palmy', 'Playing', 'installed', 'stormed', 'army', 'forc’d', 'heartlings', 'unclew', 'intervallums', '

In [3]:
#Criando tokens para cada palavra do vocabulário:

tokens = {token:integer for integer,token in enumerate(vocabulary)}
tokens

{'Changes': 0,
 'Cram': 1,
 'combat': 2,
 'prosperously': 3,
 '[Exit': 4,
 'strangers’': 5,
 'th’vein': 6,
 'Appear': 7,
 'ding': 8,
 'Since': 9,
 'hammers': 10,
 'extend': 11,
 'repined': 12,
 'auger’s': 13,
 'APPARITIONS': 14,
 '“sirrah”': 15,
 'deem’st': 16,
 'ruling': 17,
 'peregrinate': 18,
 'unhopefullest': 19,
 'mayor': 20,
 'grievance': 21,
 'Raining': 22,
 'sporting-place': 23,
 'attaint': 24,
 '“Hem': 25,
 'out-vied': 26,
 'Laid': 27,
 'ruby': 28,
 '[sings': 29,
 'Chequering': 30,
 'Intolerable': 31,
 'team': 32,
 'Disguised': 33,
 'très': 34,
 'prudent': 35,
 'foist': 36,
 'recounted': 37,
 'Actaeon’s': 38,
 'rackets': 39,
 'straining': 40,
 'Several': 41,
 '1141': 42,
 'expert': 43,
 'syrups': 44,
 'easy-held': 45,
 '“reproof': 46,
 'unbraced': 47,
 'defier': 48,
 'cunning’st': 49,
 'puzzles': 50,
 'Profess': 51,
 'couched': 52,
 '—Would': 53,
 'shrugs': 54,
 'dined—which': 55,
 'pope': 56,
 'gardeners': 57,
 'Pig-like': 58,
 'profaneness': 59,
 'Swallows': 60,
 'Ear’s': 61

In [4]:
#Criando meu Tokenizer

class meu_tokenizer:
  def __init__(self, vocabulary):
    self.str_to_int = tokens
    self.int_to_str = {i:s for s,i in tokens.items()}

  def encode(self, text):
    result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    result = [item for item in result if item.strip()]
    ids = [self.str_to_int[s] for s in result]
    return ids

  def decode(self, ids):
    tokens = [self.int_to_str[i] for i in ids]
    text = " ".join(tokens)
    return text

meu_tokenizer = meu_tokenizer(tokens)

In [5]:
#Testando

print(tokens["Jack"])

int_to_str = {i:s for s,i in tokens.items()}
int_to_str[36381]

36402


'Pilates'

In [6]:
#Mais testes

text = "This is a test with my new project!!"
print(f'Tokens: {meu_tokenizer.encode(text)}')
print(f'Decodificando: {meu_tokenizer.decode(meu_tokenizer.encode(text))}')

Tokens: [37827, 21618, 29061, 16739, 4055, 13332, 315, 13624, 16523, 16523]
Decodificando: This is a test with my new project ! !


#Inicializando com Tiktoken


In [7]:
import tiktoken
from importlib.metadata import version

tokenizer = tiktoken.get_encoding("gpt2")

print("torch version:", version("torch"))
print("tiktoken version:", version("tiktoken"))

torch version: 2.10.0+cpu
tiktoken version: 0.12.0


Testando a tokenização com tiktoken usando frase básica:

In [8]:
print(tokenizer.encode("Hello, this is a test!"))
print(tokenizer.decode(tokenizer.encode("Hello, this is a test!")))

[15496, 11, 428, 318, 257, 1332, 0]
Hello, this is a test!


Testando usando Sheakespeare:

In [9]:
url = "https://www.gutenberg.org/files/100/100-0.txt"
file_path = "shakespeare.txt"

urllib.request.urlretrieve(url, file_path)

with open(file_path, "r", encoding="utf-8") as f:
    text = f.read()

tokens = tokenizer.encode(text)
print(len(tokens))

1686450


In [10]:
x = tokens[:4]
y = tokens[1:5]

print(f'x: {x}')
print(f'y:       {y}')

x: [8162, 33303, 3963, 3336]
y:       [33303, 3963, 3336, 21965]


In [11]:
ini = 85
fim = 93

for i in range(ini + 1, fim):
  context = tokens[ini:i]
  desried = tokens[i]

  print(context, '----->', desried)

for i in range(ini + 1, fim):
  context = tokens[ini:i]
  desried = tokens[i]

  print(tokenizer.decode(context), '----->', tokenizer.decode([desried]))


[3963] -----> 3537
[3963, 3537] -----> 11357
[3963, 3537, 11357] -----> 56
[3963, 3537, 11357, 56] -----> 5357
[3963, 3537, 11357, 56, 5357] -----> 30301
[3963, 3537, 11357, 56, 5357, 30301] -----> 3185
[3963, 3537, 11357, 56, 5357, 30301, 3185] -----> 1404
 OF ----->  AN
 OF AN -----> TON
 OF ANTON -----> Y
 OF ANTONY ----->  AND
 OF ANTONY AND ----->  CLE
 OF ANTONY AND CLE -----> OP
 OF ANTONY AND CLEOP -----> AT


# Criando o dataloader

In [12]:
import torch
from torch.utils.data import Dataset, DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [13]:
def create_dataloader_v1(txt, batch_size, max_length, stride=1,
                         shuffle=True, drop_last=True, num_workers=0):
    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset, batch_size=batch_size, shuffle=shuffle, drop_last=drop_last, num_workers=num_workers)

    return dataloader

In [14]:
import os
import urllib.request

if not os.path.exists("the-verdict.txt"):
    url = "https://raw.githubusercontent.com/rasbt/LLMs-from-scratch/main/ch02/01_main-chapter-code/the-verdict.txt"
    urllib.request.urlretrieve(url, "the-verdict.txt")

with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

Testando meu dataloader:

In [15]:
dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length=4, stride=4, shuffle=False)
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

second_batch = next(data_iter)
print(second_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]
[tensor([[1807, 3619,  402,  271]]), tensor([[ 3619,   402,   271, 10899]])]


In [16]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

print(f'Inputs: \n', inputs)
print(f'Targets: \n', targets)

Inputs: 
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Targets: 
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


# Função para testar o tokenizer

In [17]:
import urllib.request
import tiktoken
import re

def analyze_text_from_url(titulo, url):
    headers = {
         "User-Agent": "Mozilla/5.0"
    }
    req = urllib.request.Request(url, headers=headers)
    response = urllib.request.urlopen(req)
    text = response.read().decode("utf-8")

    # tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")
    encoded = tokenizer.encode(text)

    words = text.split()
    num_tokens = len(encoded)
    num_words = len(words)
    tokens_per_word = num_tokens / num_words if num_words > 0 else 0

    print(f'Título do livro: {titulo}')
    print(f'Alguns tokens: {encoded[140:155]}')
    print(f'Quantidade de palavras: {num_words}')
    print(f'Quantidade de tokens: {num_tokens}')
    print(f'Quantidade de tokens por palavra {tokens_per_word:.4f}')

Testando o tokenizer

In [18]:
analyze_text_from_url("Shakespeare", "https://www.gutenberg.org/files/100/100-0.txt")

Título do livro: Shakespeare
Alguns tokens: [3336, 29125, 38, 1961, 56, 3963, 48079, 28882, 11, 4810, 1268, 5222, 3963, 37692, 44]
Quantidade de palavras: 963478
Quantidade de tokens: 1686450
Quantidade de tokens por palavra 1.7504


In [19]:
analyze_text_from_url("Alice no país das Maravilhas", "https://www.gutenberg.org/files/11/11-0.txt")

Título do livro: Alice no país das Maravilhas
Alguns tokens: [29485, 19691, 13, 220, 220, 317, 4627, 15777, 12, 33553, 198, 5870, 29485, 25197, 13]
Quantidade de palavras: 26543
Quantidade de tokens: 44560
Quantidade de tokens por palavra 1.6788


In [20]:
analyze_text_from_url("Frankenstein", "https://www.gutenberg.org/files/84/84-0.txt")

Título do livro: Frankenstein
Alguns tokens: [8270, 11, 4492, 13557, 628, 198, 1273, 13, 15722, 9228, 11, 4280, 13, 1367, 400]
Quantidade de palavras: 75060
Quantidade de tokens: 101747
Quantidade de tokens por palavra 1.3555


In [21]:
analyze_text_from_url("Wikipedia", "https://en.wikipedia.org/w/index.php?title=Python_(programming_language)&action=raw")

Título do livro: Wikipedia
Alguns tokens: [4475, 28, 22, 2901, 48609, 930, 732, 12485, 28, 31628, 13, 29412, 13, 2398, 11709]
Quantidade de palavras: 12931
Quantidade de tokens: 43175
Quantidade de tokens por palavra 3.3389


Testando com livros em português:

In [22]:
analyze_text_from_url("Iracema", "https://www.gutenberg.org/ebooks/67740.txt.utf-8")

Título do livro: Iracema
Alguns tokens: [25, 36997, 5780, 10115, 390, 978, 268, 7718, 201, 198, 201, 198, 201, 198, 220]
Quantidade de palavras: 33940
Quantidade de tokens: 83171
Quantidade de tokens por palavra 2.4505


In [23]:
analyze_text_from_url("Os Lusíadas", "https://www.gutenberg.org/files/3200/3200-0.txt")

Título do livro: Os Lusíadas
Alguns tokens: [477, 262, 2499, 286, 2940, 49824, 287, 262, 4935, 201, 198, 38, 19028, 2940, 49824]
Quantidade de palavras: 2788530
Quantidade de tokens: 4478954
Quantidade de tokens por palavra 1.6062


In [24]:
analyze_text_from_url("A Escrava Isaura", "https://www.gutenberg.org/ebooks/17059.txt.utf-8")

Título do livro: A Escrava Isaura
Alguns tokens: [329, 262, 19762, 201, 198, 201, 198, 13838, 25, 12622, 402, 13, 30928, 201, 198]
Quantidade de palavras: 49654
Quantidade de tokens: 83248
Quantidade de tokens por palavra 1.6766


# Testando o dataSet e o dataLoader

In [25]:
dataset = GPTDatasetV1(
    txt=raw_text,
    tokenizer=tokenizer,
    max_length=10,
    stride=1
)

x, y = dataset[0]

print(x)
print(y)

tensor([   40,   367,  2885,  1464,  1807,  3619,   402,   271, 10899,  2138])
tensor([  367,  2885,  1464,  1807,  3619,   402,   271, 10899,  2138,   257])


In [26]:
for batch in dataloader:
    x, y = batch
    print(x.shape, y.shape)
    break

torch.Size([8, 4]) torch.Size([8, 4])


In [27]:
x, y = dataset[0]

print(x.shape)
print(y.shape)

torch.Size([10])
torch.Size([10])


In [28]:
for x, y in dataloader:
    assert torch.equal(y[:, :-1], x[:, 1:])
    break